name: 自动化部署Hexo博客脚本
on:
  push:
    branches:
      - admin
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm -v
        npm install
        npm build
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: main
        FOLDER: .deploy_git
        