name: 自动化部署Hexo博客脚本
on:
  push:
    branches:
      - admin
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm -v
#        npm install -g cnpm@7.1.0 --registry=https://registry.npm.taobao.org
#        cnpm install
#        cnpm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        BRANCH: main
        FOLDER: public
